In [37]:
##Importing all required libraries

import numpy as np
import pandas as pd
from xgboost import XGBClassifier
import numpy as np
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingRegressor
#from xgboost import XGBRegressor
#from sklearn.tree import DecisionTreeRegressor
#from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Ridge
#from sklearn.svm import SVR
#from sklearn.linear_model import LinearRegression
#from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix ,classification_report

print('All libraries and modules have been imported sucessfully')

All libraries and modules have been imported sucessfully


In [7]:
#importing the dataset
data = pd.read_csv('/content/Data_for_UCI_named.csv')
data.sample(10)
data.shape   # 10,000 observations and 14 features

(10000, 14)

In [8]:
data.describe()
data.info()
## The Data has no null values and it is relatively clean.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [9]:
data.head()
## Target feature = stabf column

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [10]:
## Dropping stab column
data = data.drop(columns='stab',axis =1)
data

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [11]:
#plt.figure(figsize=(15,10))
#sns.heatmap(data.corr(),annot=True,annot_kws={'size':10})
#plt.show()

In [13]:
x = data.drop(axis =1,columns='stabf') ## Dropping the 'stabf'columns
y = data['stabf']
#x

data['stabf'].value_counts() ## This suggest an imbalanced Dataset

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
y_train.shape
x_train.shape

(8000, 12)

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_data = scaler.fit_transform(x_train)
train_data = pd.DataFrame(train_data)
train_data.columns = x_train.columns
print(train_data.shape)

scaler = StandardScaler()
test_data = scaler.fit_transform(x_test)
test_data = pd.DataFrame(test_data)
test_data.columns = x_test.columns
#test_data
test_data.shape


(8000, 12)


(2000, 12)

In [25]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label =   LabelEncoder()
label_y_train = label.fit_transform (y_train)
label_y_test = label.fit_transform (y_test)
label_y_train
label_y_test

## 0 represents Stable while 1 represents Unstable

array([1, 1, 0, ..., 0, 1, 1])

In [32]:
##defining a fucntion to output score results for each model


def metric_Performance_Output(model):
  mdl= model(random_state=1)
  y_pred = mdl.fit(train_data,label_y_train).predict(test_data)
  print('Accuracy:', accuracy_score(label_y_test,y_pred))
  print('Precision:',precision_score(label_y_test,y_pred))
  print('Recall:',recall_score(label_y_test,y_pred))
  print('F1_Score:',f1_score(label_y_test,y_pred))
  print('Classification Report:'+ str(model)+'\n', classification_report(label_y_test,y_pred, digits =4))
  return confusion_matrix(label_y_test,y_pred)



In [34]:
from xgboost import XGBClassifier
metric_Performance_Output(XGBClassifier)

Accuracy: 0.946
Precision: 0.950381679389313
Recall: 0.9666149068322981
F1_Score: 0.9584295612009238
Classification Report:<class 'xgboost.sklearn.XGBClassifier'>
               precision    recall  f1-score   support

           0     0.9377    0.9087    0.9230       712
           1     0.9504    0.9666    0.9584      1288

    accuracy                         0.9460      2000
   macro avg     0.9440    0.9377    0.9407      2000
weighted avg     0.9459    0.9460    0.9458      2000



array([[ 647,   65],
       [  43, 1245]])

In [35]:
from lightgbm import LGBMClassifier
metric_Performance_Output(LGBMClassifier)

Accuracy: 0.9365
Precision: 0.9421172886519421
Recall: 0.9604037267080745
F1_Score: 0.9511726259131104
Classification Report:<class 'lightgbm.sklearn.LGBMClassifier'>
               precision    recall  f1-score   support

           0     0.9258    0.8933    0.9092       712
           1     0.9421    0.9604    0.9512      1288

    accuracy                         0.9365      2000
   macro avg     0.9339    0.9268    0.9302      2000
weighted avg     0.9363    0.9365    0.9362      2000



array([[ 636,   76],
       [  51, 1237]])

In [38]:
metric_Performance_Output(RandomForestClassifier)

Accuracy: 0.928
Precision: 0.9333333333333333
Recall: 0.9565217391304348
F1_Score: 0.9447852760736196
Classification Report:<class 'sklearn.ensemble._forest.RandomForestClassifier'>
               precision    recall  f1-score   support

           0     0.9176    0.8764    0.8966       712
           1     0.9333    0.9565    0.9448      1288

    accuracy                         0.9280      2000
   macro avg     0.9255    0.9165    0.9207      2000
weighted avg     0.9277    0.9280    0.9276      2000



array([[ 624,   88],
       [  56, 1232]])

In [39]:
metric_Performance_Output(ExtraTreesClassifier)

Accuracy: 0.926
Precision: 0.9191176470588235
Recall: 0.9704968944099379
F1_Score: 0.9441087613293052
Classification Report:<class 'sklearn.ensemble._forest.ExtraTreesClassifier'>
               precision    recall  f1-score   support

           0     0.9406    0.8455    0.8905       712
           1     0.9191    0.9705    0.9441      1288

    accuracy                         0.9260      2000
   macro avg     0.9299    0.9080    0.9173      2000
weighted avg     0.9268    0.9260    0.9250      2000



array([[ 602,  110],
       [  38, 1250]])

In [41]:
## Hyper Parameter Tuning

## Defining Parameters

n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,'min_samples_leaf': min_samples_leaf,'min_samples_split': min_samples_split,'max_features': max_features}

In [42]:
from sklearn.model_selection import RandomizedSearchCV
etc = ExtraTreesClassifier(random_state=1)
rsv = RandomizedSearchCV(etc,param_distributions = hyperparameter_grid, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1,random_state=1)
rsv.fit(train_data,label_y_train)
rsv.best_params_

Fitting 5 folds for each of 10 candidates, totalling 50 fits


{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [44]:
mdl= ExtraTreesClassifier(n_estimators= 1000, min_samples_split= 2,min_samples_leaf= 8,max_features= None)

y_pred = mdl.fit(train_data,label_y_train).predict(test_data)
print('Accuracy:', accuracy_score(label_y_test,y_pred))
print('Precision:',precision_score(label_y_test,y_pred))
print('Recall:',recall_score(label_y_test,y_pred))
print('F1_Score:',f1_score(label_y_test,y_pred))
print('Classification Report:'+'\n', classification_report(label_y_test,y_pred, digits =4))
confusion_matrix(label_y_test,y_pred)

Accuracy: 0.929
Precision: 0.9314759036144579
Recall: 0.9604037267080745
F1_Score: 0.9457186544342508
Classification Report:
               precision    recall  f1-score   support

           0     0.9241    0.8722    0.8974       712
           1     0.9315    0.9604    0.9457      1288

    accuracy                         0.9290      2000
   macro avg     0.9278    0.9163    0.9216      2000
weighted avg     0.9289    0.9290    0.9285      2000



array([[ 621,   91],
       [  51, 1237]])

In [ ]:
## Accuracy for ExtraTreeClassifier Model (0.929- with Hyperparameter Tuning ) is greater than the accuracy without Hyperparameter Tuning (0.926)

In [45]:
## feature importance for optimized ExtraTreeClassifier Model
a= mdl.feature_importances_
pd.DataFrame(a,train_data.columns).reset_index().sort_values(by=0,ascending =False)


## tau2 is the best feature while p1 is the least feature impacting on the model.

index         0
1   tau2  0.140471
0   tau1  0.137737
3   tau4  0.135085
2   tau3  0.134788
10    g3  0.112297
11    g4  0.109113
9     g2  0.108452
8     g1  0.102564
5     p2  0.005402
6     p3  0.005343
7     p4  0.004967
4     p1  0.003781